import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

import Navbar from "@/components/section/navbar";
import { DataProvider } from "@/context/data-provider";
import { QueryProvider } from "@/context/query-provider";
import { SessionProvider } from "next-auth/react";
import { Instrument_Serif } from "next/font/google";
import { getAllAlbums } from "./action/album";
import { getAllArtists } from "./action/artist";
import { getAllPoets } from "./action/poet";
import { getAllTags } from "./action/tag";

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
  variable: "--font-instrument-serif",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const artists = await getAllArtists();
  const albums = await getAllAlbums();
  const poets = await getAllPoets();
  const tags = await getAllTags();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} antialiased`}
      >
        <SessionProvider>
          <QueryProvider>
            <DataProvider
              initialArtists={artists}
              initialAlbums={albums}
              initialPoets={poets}
              initialTags={tags}
            >
              <Navbar />
              {children}
              <Toaster />
            </DataProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
